# Generated by Django 3.0.4 on 2020-03-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200322_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cuttingmaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CuttingMaster'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sewingmaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SewingMaster'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subemploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SubEmploy'),
        ),
    ]
